//! Complete pinned upstream workflow. Assets, examples and tests accompany the skill.
use crate::agent::harness::{confined_publish_new_no_symlinks, confined_read_limited_no_symlinks};
use std::path::Path;
pub(crate) const FILES: &[(&str, &[u8])] = &[
    (
        ".github/workflows/tests.yml",
        include_bytes!("../../../research/labyrinth/upstream/.github/workflows/tests.yml"),
    ),
    (
        ".gitignore",
        include_bytes!("../../../research/labyrinth/upstream/.gitignore"),
    ),
    (
        "CHANGELOG.md",
        include_bytes!("../../../research/labyrinth/upstream/CHANGELOG.md"),
    ),
    (
        "LICENSE",
        include_bytes!("../../../research/labyrinth/upstream/LICENSE"),
    ),
    (
        "MAINTAINING.md",
        include_bytes!("../../../research/labyrinth/upstream/MAINTAINING.md"),
    ),
    (
        "README.md",
        include_bytes!("../../../research/labyrinth/upstream/README.md"),
    ),
    (
        "SKILL.md",
        include_bytes!("../../../research/labyrinth/upstream/SKILL.md"),
    ),
    (
        "agents/openai.yaml",
        include_bytes!("../../../research/labyrinth/upstream/agents/openai.yaml"),
    ),
    (
        "assets/campaign.svg",
        include_bytes!("../../../research/labyrinth/upstream/assets/campaign.svg"),
    ),
    (
        "assets/dashboard-board.png",
        include_bytes!("../../../research/labyrinth/upstream/assets/dashboard-board.png"),
    ),
    (
        "assets/dashboard-frontier.png",
        include_bytes!("../../../research/labyrinth/upstream/assets/dashboard-frontier.png"),
    ),
    (
        "assets/dashboard-graph.png",
        include_bytes!("../../../research/labyrinth/upstream/assets/dashboard-graph.png"),
    ),
    (
        "assets/dashboard-map.png",
        include_bytes!("../../../research/labyrinth/upstream/assets/dashboard-map.png"),
    ),
    (
        "assets/dashboard-sota.png",
        include_bytes!("../../../research/labyrinth/upstream/assets/dashboard-sota.png"),
    ),
    (
        "assets/hero.svg",
        include_bytes!("../../../research/labyrinth/upstream/assets/hero.svg"),
    ),
    (
        "assets/loop.svg",
        include_bytes!("../../../research/labyrinth/upstream/assets/loop.svg"),
    ),
    (
        "assets/social-preview.png",
        include_bytes!("../../../research/labyrinth/upstream/assets/social-preview.png"),
    ),
    (
        "assets/tiers.svg",
        include_bytes!("../../../research/labyrinth/upstream/assets/tiers.svg"),
    ),
    (
        "docs/codex-testing.md",
        include_bytes!("../../../research/labyrinth/upstream/docs/codex-testing.md"),
    ),
    (
        "docs/tutorial.md",
        include_bytes!("../../../research/labyrinth/upstream/docs/tutorial.md"),
    ),
    (
        "examples/README.md",
        include_bytes!("../../../research/labyrinth/upstream/examples/README.md"),
    ),
    (
        "examples/prompts.md",
        include_bytes!("../../../research/labyrinth/upstream/examples/prompts.md"),
    ),
    (
        "examples/triangle-counts/README.md",
        include_bytes!("../../../research/labyrinth/upstream/examples/triangle-counts/README.md"),
    ),
    (
        "examples/triangle-counts/events.jsonl",
        include_bytes!(
            "../../../research/labyrinth/upstream/examples/triangle-counts/events.jsonl"
        ),
    ),
    (
        "examples/triangle-counts/exhaustive_n8.py",
        include_bytes!(
            "../../../research/labyrinth/upstream/examples/triangle-counts/exhaustive_n8.py"
        ),
    ),
    (
        "examples/triangle-counts/knowledge.json",
        include_bytes!(
            "../../../research/labyrinth/upstream/examples/triangle-counts/knowledge.json"
        ),
    ),
    (
        "examples/triangle-counts/make_example.py",
        include_bytes!(
            "../../../research/labyrinth/upstream/examples/triangle-counts/make_example.py"
        ),
    ),
    (
        "examples/triangle-counts/sota.json",
        include_bytes!("../../../research/labyrinth/upstream/examples/triangle-counts/sota.json"),
    ),
    (
        "references/campaigns.md",
        include_bytes!("../../../research/labyrinth/upstream/references/campaigns.md"),
    ),
    (
        "references/codex.md",
        include_bytes!("../../../research/labyrinth/upstream/references/codex.md"),
    ),
    (
        "references/compute.md",
        include_bytes!("../../../research/labyrinth/upstream/references/compute.md"),
    ),
    (
        "references/lessons.md",
        include_bytes!("../../../research/labyrinth/upstream/references/lessons.md"),
    ),
    (
        "references/loop.md",
        include_bytes!("../../../research/labyrinth/upstream/references/loop.md"),
    ),
    (
        "references/saturation.md",
        include_bytes!("../../../research/labyrinth/upstream/references/saturation.md"),
    ),
    (
        "references/schema.md",
        include_bytes!("../../../research/labyrinth/upstream/references/schema.md"),
    ),
    (
        "templates/briefs/attack.md",
        include_bytes!("../../../research/labyrinth/upstream/templates/briefs/attack.md"),
    ),
    (
        "templates/briefs/referee.md",
        include_bytes!("../../../research/labyrinth/upstream/templates/briefs/referee.md"),
    ),
    (
        "templates/briefs/writer.md",
        include_bytes!("../../../research/labyrinth/upstream/templates/briefs/writer.md"),
    ),
    (
        "templates/dashboard.html",
        include_bytes!("../../../research/labyrinth/upstream/templates/dashboard.html"),
    ),
    (
        "templates/lab.py",
        include_bytes!("../../../research/labyrinth/upstream/templates/lab.py"),
    ),
    (
        "tests/test_codex.py",
        include_bytes!("../../../research/labyrinth/upstream/tests/test_codex.py"),
    ),
    (
        "tests/test_lab.py",
        include_bytes!("../../../research/labyrinth/upstream/tests/test_lab.py"),
    ),
    (
        "tests/test_skill.py",
        include_bytes!("../../../research/labyrinth/upstream/tests/test_skill.py"),
    ),
    (
        "tools/codex_smoke.py",
        include_bytes!("../../../research/labyrinth/upstream/tools/codex_smoke.py"),
    ),
    (
        "tools/make_graphics.py",
        include_bytes!("../../../research/labyrinth/upstream/tools/make_graphics.py"),
    ),
    (
        "tools/screenshots.py",
        include_bytes!("../../../research/labyrinth/upstream/tools/screenshots.py"),
    ),
];
pub(crate) fn initialize(workspace: &Path) -> Result<(), String> {
    for (name, bytes) in FILES {
        let rel = std::path::PathBuf::from("labyrinth/workflow").join(name);
        if std::fs::symlink_metadata(workspace.join(&rel)).is_ok() {
            confined_read_limited_no_symlinks(workspace, &rel, 16 * 1024 * 1024)?
                .ok_or_else(|| format!("{} exceeds workflow byte budget", rel.display()))?;
        } else {
            confined_publish_new_no_symlinks(workspace, &rel, bytes)?;
        }
    }
    Ok(())
}
