// Tests for reflex-reconfigure: turning concluded config hypotheses into the
// .angel.auto.env launch overlay. Pure selection + rendering, hand-built graphs.

import { test } from 'node:test'
import assert from 'node:assert/strict'

import CausalGraph, { EDGE_TYPE } from '../../lib/research/CausalGraph.js'
import { seedConfigHypotheses, configHypothesisId } from '../../scripts/config-causal.mjs'
import {
  selectWinners,
  renderOverlay,
  renderProposals,
  isSecretName,
  TIER_A_KNOBS,
  CONCLUDE_THRESHOLD,
} from '../../scripts/reflex-reconfigure.mjs'

const NOW = '2026-07-04T00:00:00.000Z'
const AGG_ACC = configHypothesisId('agg', 'codex-run', 'accuracy_pct')
const AGG_LONGCAT = configHypothesisId('agg', 'longcat', 'accuracy_pct')
const SPIN_ACC = configHypothesisId('spin_limit', '8', 'spin_stop_rate')

// Add `n` interventional SUPPORTS edges so belief clears the 0.85 threshold
// (3 × 0.8 in log-odds → ~0.92). Src nodes need not exist for beliefProbability.
function support(
  graph,
  hypId,
  { n = 3, conf = 0.8, label = 'bench Δaccuracy +10 (control-code-v2)' } = {},
) {
  for (let i = 0; i < n; i++) {
    graph.addEdge({
      src: `exp_c${i}_${hypId}`,
      dst: hypId,
      type: EDGE_TYPE.SUPPORTS,
      confidence: conf,
      label,
    })
  }
}

const seeded = () => {
  const g = new CausalGraph()
  seedConfigHypotheses(g, { now: NOW })
  return g
}

test('a concluded, interventional-backed routing win is selected as Tier A', () => {
  const g = seeded()
  support(g, AGG_ACC)
  const winners = selectWinners(g)
  const agg = winners.find((w) => w.knobName === 'ANGEL_SOTA_MOA_AGG_CLUB')
  assert.ok(agg, 'AGG win selected')
  assert.equal(agg.value, 'codex-run')
  assert.equal(agg.tier, 'A')
  assert.ok(agg.belief >= CONCLUDE_THRESHOLD)
  assert.ok(agg.benchEvidence.includes('bench'))
})

test('observational-only evidence (no SUPPORTS edge) is NOT selected', () => {
  const g = seeded()
  // Simulate M2 observational evidence: attach `observed`, add NO edge.
  g.updateNode(AGG_ACC, { observed: { samples: 20, gradient: 0.6, baseline: 0.6 } })
  assert.equal(selectWinners(g).length, 0)
})

test('below the belief threshold is NOT selected', () => {
  const g = seeded()
  support(g, AGG_ACC, { n: 1 }) // one 0.8 edge → belief ≈ 0.69 < 0.85
  assert.equal(selectWinners(g).length, 0)
})

test('a contradicted hypothesis is never written', () => {
  const g = seeded()
  support(g, AGG_LONGCAT) // even with supports…
  g.updateNode(AGG_LONGCAT, { outcome: 'negative' }) // …a negative conclusion excludes it
  assert.ok(!selectWinners(g).some((w) => w.value === 'longcat'))
})

test('one winner per knob — the highest belief value wins', () => {
  const g = seeded()
  support(g, AGG_ACC, { n: 4 }) // codex-run, stronger
  support(g, configHypothesisId('agg', 'deepseek', 'accuracy_pct'), { n: 3 }) // deepseek, weaker
  const aggWins = selectWinners(g).filter((w) => w.knobName === 'ANGEL_SOTA_MOA_AGG_CLUB')
  assert.equal(aggWins.length, 1)
  assert.equal(aggWins[0].value, 'codex-run')
})

test('renderOverlay emits Tier A live, Tier B commented, with evidence + header', () => {
  const g = seeded()
  support(g, AGG_ACC) // Tier A routing knob
  support(g, SPIN_ACC) // Tier B guardrail knob
  const overlay = renderOverlay(selectWinners(g), { now: NOW })
  // header + non-editable warning
  assert.ok(overlay.includes('GENERATED by reflex'))
  assert.ok(overlay.includes('Hand pins in .angel.env win'))
  // Tier A is a LIVE line; Tier B is COMMENTED
  assert.ok(/^ANGEL_SOTA_MOA_AGG_CLUB=codex-run$/m.test(overlay))
  assert.ok(/^# ANGEL_SPIN_LIMIT=8$/m.test(overlay))
  // evidence rides in a comment
  assert.ok(/# p=0\.\d+ · bench/m.test(overlay))
  // never the raw secret pattern, never .angel.env writes
  assert.ok(!/KEY|TOKEN|SECRET/.test(overlay.replace(/#.*/g, '')))
})

test('secret-named / non-catalog knobs are refused by both select and render', () => {
  assert.equal(isSecretName('ANGEL_OPENAI_API_KEY'), true)
  assert.equal(isSecretName('ANGEL_SOTA_MOA_AGG_CLUB'), false)
  const g = seeded()
  // A hand-forged reflex hypothesis on a secret-ish, non-catalog knob.
  g.addNode({
    id: 'reflex_rogue_x_accuracy_pct',
    type: 'hypothesis',
    projectId: 'reflex',
    knobName: 'ANGEL_ROGUE_API_KEY',
    knobValue: 'leak',
    metric: { name: 'accuracy_pct' },
  })
  support(g, 'reflex_rogue_x_accuracy_pct')
  assert.ok(!selectWinners(g).some((w) => w.knobName === 'ANGEL_ROGUE_API_KEY'))
  // even if one sneaked into render input, it is filtered
  const forced = renderOverlay(
    [{ knobName: 'ANGEL_ROGUE_API_KEY', value: 'leak', tier: 'A', belief: 0.99 }],
    { now: NOW },
  )
  assert.ok(!forced.includes('ANGEL_ROGUE_API_KEY'))
})

test('all Tier A knobs are catalog routing knobs; proposals lists Tier B', () => {
  for (const k of TIER_A_KNOBS) assert.ok(k.startsWith('ANGEL_'))
  const g = seeded()
  support(g, SPIN_ACC)
  const md = renderProposals(selectWinners(g), { now: NOW })
  assert.ok(md.includes('ANGEL_SPIN_LIMIT=8'))
  assert.ok(md.includes('.angel.env'))
})
